### ISSUE TITLE
"Abortedmix incompatible Qt library"

### ISSUE THREAD

**Issue by thx1111** [lirios/packages#3]
Running current Arch with packages from "Server = https://repo.liri.io/archlinux/unstable/x86_64",  then "liri-session" gives:

Abortedmix incompatible Qt library (version 0x50a01) with this library (version 0x50b01)eters).

including what appears to be output formatting corruption, probably a result of not terminating error messages with proper "new line" characters.

Is there a problem with the Arch Qt library build?  Or, with the Arch liri build?

Arch packages include, for instance,
liri-wayland-git 20180427.1832.d930af60-1
qt5-gsettings-git 20180412.97.ab869fd-1

**Comment by plfiorini** [comment]
I have stopped rebuilds on the CI until some work on the modularization front is done.
Some programs such as liri-screenshot and liri-screencast were moved out of liri-workspace.
Will enable rebuilds in the near future.
The bug stays open until then.
