### ISSUE TITLE
liri-shell is missing the install file

### ISSUE THREAD

**Issue by SolarAquarion** [lirios/packages#5]
and you should do 

" find -name PKGBUILD -execdir sh -c 'makepkg --printsrcinfo > .SRCINFO' \;" 

to find other packaging problems

**Comment by SolarAquarion** [comment]
@plfiorini fluid-git is missing qt-wayland, also clang is a makedepend

**Comment by plfiorini** [comment]
* Add `liri-shell-git` install file
* Add missing dep to `fluid-git`
* Every subdir already has a .SRCINFO

Why should I add clang as a makedepend to `fluid-git`?

**Comment by SolarAquarion** [comment]
Because qdoc requires clang in order for the qt docs to build.  See how
qt5-tools has clang as a optional dependency

**Comment by plfiorini** [comment]
Done

**Comment by SolarAquarion** [comment]
anyway, i think you can safely remove the install file, because there is
automatic compilation of gschema's thanks to the power of "hooks"

**Comment by plfiorini** [comment]
Done

**Comment by SolarAquarion** [comment]
I think you need to port xdg portal to cmake

**Comment by plfiorini** [comment]
It is (see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xdg-desktop-portal-liri-git) but it hasn't been copied over here from AUR.
